apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-payment
  labels:
    app: fcg-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-payment
  template:
    metadata:
      labels:
        app: fcg-payment
    spec:
      containers:
        - name: fcg-payment
          image: gsramos/fcg-pagamentos:v10
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: payment-env-secret
              prefix: "ConnectionStrings__"
          env: 
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production" 
            - name: ASPNETCORE_URLS
              value: "http://+:8080" 
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"      
            limits:
              memory: "512Mi"
              cpu: "200m"